CREATE TABLE public.formula (
    id BIGINT NOT NULL,
    code BOOLEAN NOT NULL,
    description TEXT,
    price DOUBLE PRECISION,
    promotionnal_price DOUBLE PRECISION,
    title VARCHAR(255)
);

ALTER TABLE public.formula ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.formula_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);

ALTER TABLE ONLY public.formula
    ADD CONSTRAINT formula_pkey PRIMARY KEY (id);
