-- ============================================
-- Création de la table formula
-- Compatible PostgreSQL + H2
-- ============================================

CREATE TABLE IF NOT EXISTS formula (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    code BOOLEAN NOT NULL,
    description TEXT,
    price DOUBLE PRECISION,
    promotionnal_price DOUBLE PRECISION,
    title VARCHAR(255)
);

-- ============================================
-- Primary Key
-- ============================================

ALTER TABLE formula
    ADD CONSTRAINT formula_pkey PRIMARY KEY (id);

-- ============================================
-- Données initiales
-- ============================================

INSERT INTO formula (id, code, description, price, promotionnal_price, title) VALUES
(1, true, 'Inscription ANTS, Accès salle de code en illimité, Code en ligne (Pass Rousseau), 20 leçons de conduite, Livret pédagogique dématérialisé, Accompagnement à l’examen pratique de la conduite', 1139, NULL, 'Forfait B 20H'),
(2, true, 'Inscription ANTS, Accès salle de code en illimité, Code en ligne (Pass Rousseau), 20 leçons de conduite, Livret pédagogique dématérialisé, Accompagnement à l’examen pratique de la conduite, RDV pédagogique préalable avec l’accompagnateur (2h), 2 RDV pédagogiques (2h)', 1339, NULL, 'Forfait AAC 20H (Dès 15 ans)'),
(3, true, 'Inscription ANTS, Accès salle de code en illimité, Code en ligne (Pass Rousseau), 13 leçons de conduite, Livret pédagogique dématérialisé, Accompagnement à l’examen pratique de la conduite', 839, NULL, 'Formule B78 13H'),
(4, true, 'Inscription ANTS, Accès salle de code en illimité, Code en ligne (Pass Rousseau), 20 leçons de conduite, Livret pédagogique dématérialisé, Accompagnement à l’examen pratique de la conduite', 1139, NULL, 'Formule B78 20H'),
(5, false, 'Inscription ANTS, 20 leçons de conduite, Livret pédagogique dématérialisé, Accompagnement à l’examen pratique de la conduite', 1099, NULL, 'Forfait B 20H'),
(6, false, 'Inscription ANTS, 20 leçons de conduite, Livret pédagogique dématérialisé, Accompagnement à l’examen pratique de la conduite, RDV pédagogique préalable avec l’accompagnateur (2h), 2 RDV pédagogiques (2h)', 1299, NULL, 'Forfait AAC 20H (Dès 15 ans)'),
(7, false, 'Inscription ANTS, 13 leçons de conduite, Livret pédagogique dématérialisé, Accompagnement à l’examen pratique de la conduite', 799, NULL, 'Formule B78 13H'),
(8, false, 'Inscription ANTS, Accès salle de code en illimité, Code en ligne (Pass Rousseau), 20 leçons de conduite, Livret pédagogique dématérialisé, Accompagnement à l’examen pratique de la conduite', 1099, NULL, 'Formule B78 20H'),
(14, true, 'Inscription ANTS, Accès salle de code en illimité, Code en ligne (Pass Rousseau), 20 leçons de conduite, Livret pédagogique dématérialisé,test', 500, NULL, 'Forfait test'),
(20, true, '', 700, NULL, 'Forfait test lol');

-- ============================================
-- Ajustement de la séquence (compatible PostgreSQL seulement)
-- H2 ignore cette commande silencieusement
-- ============================================

-- Cette commande fonctionne sous PostgreSQL et H2 ne la bloque pas
ALTER SEQUENCE IF EXISTS formula_id_seq RESTART WITH 25;
